###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

myapp-mailhog:
  image: phpdockerio/mailhog:latest
  container_name: myapp-mailhog
  ports:
    - "8125:8025"

myapp-mysql:
  image: mysql:5.7
  container_name: myapp-mysql
  volumes:
      - ../mysql:/var/lib/mysql
  ports:
    - "8106:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=myapp
    - MYSQL_USER=myapp
    - MYSQL_PASSWORD=myapp

myapp-mysql-test:
  image: mysql:5.7
  container_name: myapp-mysql-test
  volumes:
      - ../mysql-test:/var/lib/mysql
  ports:
    - "8107:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=myapp
    - MYSQL_USER=myapp
    - MYSQL_PASSWORD=myapp

myapp-nginx:
  image: phpdockerio/nginx:latest
  container_name: myapp-nginx
  volumes:
    - ../cakephp:/var/www/myapp
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8180:80"
  links:
   - myapp-php-fpm

myapp-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: myapp-php-fpm
  volumes:
    - ../cakephp:/var/www/myapp
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  environment:
    - DATABASE_TEST_URL=mysql://myapp:myapp@myapp-mysql-test/myapp
  links:
    - myapp-mailhog
    - myapp-mysql
    - myapp-mysql-test

myapp-phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: myapp-phpmyadmin
  ports:
   - "8181:80"
  environment:
    - PMA_HOST=myapp-mysql
    - PMA_USER=myapp
    - PMA_PASSWORD=myapp
  links:
    - myapp-mysql
